# Generated by Django 3.2.9 on 2021-12-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('book_image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
