# Generated by Django 3.2.9 on 2021-12-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_book_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default='{}')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.user_reg')),
            ],
        ),
    ]
