# Generated by Django 3.2.9 on 2021-12-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_cart_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='password',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='cart_details',
        ),
    ]
